[package]
name = "egui_extended"
version = "0.3.0"
edition = "2021"



[dependencies]
egui = "^0.22"
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
eframe = "^0.22"

# [features]
# serde = ["dep:serde", "egui/serde"]
